### ISSUE TITLE
Support localization of FSB and UOSB

### ISSUE THREAD

**Issue by drgoonic** [brasstax/ffrkbot#25]
Due to Enlir swapping his spreadsheet naming conventions the FSB and UOSB bot lookups fail:

FSB > Glint
UOSB > ASB

**Comment by drgoonic** [comment]
soulbreak-bot-utils.js should lose fsb,uosb in favor of glint, asb
Also alias update magic 👍

**Comment by brasstax** [comment]
This is fixed in the newest master.
