### ISSUE TITLE
Compressing ability information output

### ISSUE THREAD

**Issue by Netmonmatt** [brasstax/ffrkbot#9]
The current command output throws out data in this format:

Ability name: Firaja
Description: Magical Attack
Multiplier: 9
Element: Fire
Type: Black Magic
Target: Single
Soul Break charge: 60
Cast time: 1.8

This is quite a few lines, especially for an active chat room. Compressing the lines would make the bot much friendlier on the screen real estate and make it feel less spammy. Something like this:

Ability name: Firaja
Description: Magical Attack
Multiplier: 9  ||  Element: Fire
Type: Black Magic  ||  Target: Single
Soul Break Charge: 60  ||  Cast Time: 1.8

Putting names and descriptions on the same line may be a problem because some descriptions are way more complex, but compressing the other data to two entries a line would kill a lot of wasted space.

**Comment by brasstax** [comment]
Because it makes a bit more sense, I'm going to put `Type` and `Element` in the same line, and put `Target` and `Multiplier` on the same line.

**Comment by brasstax** [comment]
This is done.
